@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam1AZW1haWwuY29tLmJyIiwiaWF0IjoxNzQzOTg2MzAxLCJleHAiOjE3NDM5ODk5MDF9.qgFlTL1vEbn_6vlArw-heYh7VvNp4y83WQ77iGyUmyc

POST http://localhost:3000/projects
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Lista de compras do Jose",
    "description": "lista basica"
}

###

GET http://localhost:3000/projects
Authorization: Bearer {{token}}