@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam1AZW1haWwuY29tLmJyIiwiaWF0IjoxNzQzOTg5MTAzLCJleHAiOjE3NDM5OTI3MDN9.zQ3KQlp2HWF7IzJMVvOgW_HLOmsy-h0Fi7AOgZrB_UY

POST http://localhost:3000/tasks
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Finalizar curso de nest - Jose",
    "projectId": 1,
    "status": "pending"
}

###

GET http://localhost:3000/tasks
Authorization: Bearer {{token}}